// 多语言支持
const translations = {
    'zh': {
        'nav.home': '首页',
        'nav.about': '关于我',
        'nav.media': '媒体中心',
        'nav.schedule': '演出日程',
        'nav.contact': '联系我',
        'hero.title': '欢迎来到我的世界',
        'hero.subtitle': '探索艺术、音乐与文化的交融',
        'hero.button': '了解更多',
        'about.subtitle': '关于我',
        'about.text1': '我是一位热爱艺术与音乐的专业人士...',
        'about.text2': '我的作品融合了东西方文化元素...',
        'about.bio1': '我是一位充满激情的艺术家，致力于将古典美学与现代元素融合，创造出独特的艺术体验。多年来，我在音乐、舞蹈和视觉艺术领域不断探索，寻求突破传统界限的表达方式。',
        'about.bio2': '我的作品曾在欧洲、亚洲和北美多个国家展出和演出，获得了广泛的认可和好评。我相信艺术的力量可以跨越语言和文化的障碍，连接不同背景的人们。',
        'about.bio3': '除了创作，我也热衷于艺术教育和文化交流。我曾在多所艺术院校担任客座讲师，并参与了多个国际文化交流项目，希望能够激发更多年轻人对艺术的热爱和创造力。',
        'about.resumeCn': '下载中文简历',
        'about.resumeEn': 'Download English Resume',
        'about.achievements': '成就与荣誉',
        'about.achievement1': '2022年 国际艺术博览会金奖',
        'about.achievement2': '2020年 欧洲文化交流贡献奖',
        'about.achievement3': '2018年 亚洲青年艺术家奖',
        'about.achievement4': '2016年 世界音乐大赛最佳作曲奖',
        'features.title': '过往活动',
        'features.item1.title': '音乐创作',
        'features.item1.desc': '融合古典与现代元素的原创音乐作品',
        'features.item2.title': '舞台表演',
        'features.item2.desc': '充满激情与创意的现场演出',
        'features.item3.title': '文化探索',
        'features.item3.desc': '跨越不同文化的艺术交流与探索',
        'media.title': '媒体中心',
        'media.description': '这里展示我的最新演出视频和媒体内容',
        'media.featured': '精选视频',
        'media.featuredCaption': '最新音乐录影带《艺术的旋律》',
        'media.gallery': '视频库',
        'media.video1.title': '最新演出',
        'media.video1.description': '2025年春季音乐会现场',
        'media.video1.date': '2023年3月15日',
        'media.video2.title': '创作过程纪实',
        'media.video2.date': '2023年1月22日',
        'media.video3.title': '艺术家访谈',
        'media.video3.date': '2022年11月10日',
        'media.video4.title': '幕后花絮 - 录音棚',
        'media.video4.date': '2022年9月5日',
        'schedule.title': '演出日程',
        'schedule.description': '查看我的演出和活动安排',
        'schedule.dateHeader': '日期',
        'schedule.eventHeader': '活动',
        'schedule.locationHeader': '地点',
        'schedule.ticketHeader': '购票',
        'schedule.event1.date': '2023年10月15日',
        'schedule.event1.location': '北京国家大剧院',
        'schedule.event1.description': '春季音乐会',
        'schedule.event1': '古典音乐会',
        'schedule.location1': '柏林音乐厅',
        'schedule.event2.date': '2024年11月2日',
        'schedule.event2.location': '上海音乐厅',
        'schedule.event2.description': '独奏会',
        'schedule.event2': '现代舞表演',
        'schedule.location2': '巴黎歌剧院',
        'schedule.event3': '艺术展览开幕式',
        'schedule.location3': '伦敦国家美术馆',
        'schedule.event3.date': '2025年11月20日',
        'schedule.event4': '新年音乐会',
        'schedule.location4': '维也纳金色大厅',
        'schedule.event4.date': '2024年12月5日',
        'schedule.event5': '亚洲巡演 - 北京',
        'schedule.location5': '北京国家大剧院',
        'schedule.event5.date': '2026年1月18日',
        'schedule.ticketButton': '购票',
        'schedule.reserveButton': '预约',
        'schedule.comingSoonButton': '即将开售',
        'schedule.detailsButton': '活动详情',
        'contact.title': '联系我',
        'contact.description': '有任何问题或合作意向，请随时与我联系',
        'contact.formTitle': '发送消息',
        'contact.nameLabel': '您的姓名',
        'contact.emailLabel': '电子邮箱',
        'contact.subjectLabel': '主题',
        'contact.messageLabel': '消息内容',
        'contact.submitBtn': '发送消息',
        'contact.infoTitle': '联系方式',
        'contact.email': '邮箱: contact@dansworld.com',
        'contact.phone': '电话: +49 123 4567 8910',
        'contact.address': '地址: 柏林艺术区, 德国',
        'contact.facebook': 'Facebook',
        'contact.instagram': 'Instagram',
        'contact.twitter': 'Twitter',
        'contact.youtube': 'YouTube',
        'contact.form.name': '姓名',
        'contact.form.email': '电子邮箱',
        'contact.form.message': '留言',
        'contact.form.submit': '发送'
    },
    'en': {
        'nav.home': 'Home',
        'nav.about': 'About Me',
        'nav.media': 'Media Center',
        'nav.schedule': 'Schedule',
        'nav.contact': 'Contact',
        'hero.title': 'Welcome to My World',
        'hero.subtitle': 'Exploring the Fusion of Art, Music and Culture',
        'hero.button': 'Learn More',
        'about.subtitle': 'About Me',
        'about.text1': 'I am a professional passionate about art and music...',
        'about.text2': 'My works blend elements of Eastern and Western cultures...',
        'about.bio1': 'I am a passionate artist dedicated to blending classical aesthetics with modern elements to create unique artistic experiences. Over the years, I have explored music, dance, and visual arts, seeking expressive ways to break traditional boundaries.',
        'about.bio2': 'My works have been exhibited and performed in various countries across Europe, Asia, and North America, receiving widespread recognition and acclaim. I believe in the power of art to transcend language and cultural barriers, connecting people from different backgrounds.',
        'about.bio3': 'In addition to creating art, I am also passionate about art education and cultural exchange. I have served as a guest lecturer at several art institutions and participated in numerous international cultural exchange programs, hoping to inspire more young people to love and create art.',
        'about.resumeCn': 'Download Chinese Resume',
        'about.resumeEn': 'Download English Resume',
        'about.achievements': 'Achievements and Honors',
        'about.achievement1': '2022 International Art Fair Gold Award',
        'about.achievement2': '2020 European Cultural Exchange Contribution Award',
        'about.achievement3': '2018 Asian Young Artist Award',
        'about.achievement4': '2016 World Music Competition Best Composition Award',
        'features.title': 'Gallery',
        'features.item1.title': 'Music Creation',
        'features.item1.desc': 'Original music works blending classical and modern elements',
        'features.item2.title': 'Stage Performance',
        'features.item2.desc': 'Passionate and creative live performances',
        'features.item3.title': 'Cultural Exploration',
        'features.item3.desc': 'Artistic exchanges and explorations across different cultures',
        'media.title': 'Media Center',
        'media.description': 'Here are my latest performance videos and media content',
        'media.featured': 'Featured Video',
        'media.featuredCaption': 'Latest Music Video "Melody of Art"',
        'media.gallery': 'Video Gallery',
        'media.video1.title': 'Latest Performance',
        'media.video1.description': 'Spring Concert 2025 Live',
        'media.video1.date': 'March 15, 2023',
        'media.video2.title': 'Creative Process Documentary',
        'media.video2.date': 'January 22, 2023',
        'media.video3.title': 'Artist Interview',
        'media.video3.date': 'November 10, 2022',
        'media.video4.title': 'Behind the Scenes - Recording Studio',
        'media.video4.date': 'September 5, 2022',
        'schedule.title': 'Performance Schedule',
        'schedule.description': 'Check out my upcoming performances and events',
        'schedule.dateHeader': 'Date',
        'schedule.eventHeader': 'Event',
        'schedule.locationHeader': 'Location',
        'schedule.ticketHeader': 'Tickets',
        'schedule.event1.date': 'October 15, 2023',
        'schedule.event1.location': 'National Centre for the Performing Arts, Beijing',
        'schedule.event1.description': 'Spring Concert',
        'schedule.event1': 'Classical Music Concert',
        'schedule.location1': 'Berlin Concert Hall',
        'schedule.event2.date': 'November 2, 2024',
        'schedule.event2.location': 'Shanghai Concert Hall',
        'schedule.event2.description': 'Solo Recital',
        'schedule.event2': 'Modern Dance Performance',
        'schedule.location2': 'Paris Opera House',
        'schedule.event3': 'Art Exhibition Opening',
        'schedule.location3': 'National Gallery, London',
        'schedule.event3.date': 'November 20, 2025',
        'schedule.event4': 'New Year Concert',
        'schedule.location4': 'Vienna Golden Hall',
        'schedule.event4.date': 'December 5, 2024',
        'schedule.event5': 'Asia Tour - Beijing',
        'schedule.location5': 'National Centre for the Performing Arts, Beijing',
        'schedule.event5.date': 'January 18, 2026',
        'schedule.ticketButton': 'Buy Tickets',
        'schedule.reserveButton': 'Reserve',
        'schedule.comingSoonButton': 'Coming Soon',
        'schedule.detailsButton': 'Event Details',
        'contact.title': 'Contact Me',
        'contact.description': 'If you have any questions or cooperation intentions, please feel free to contact me',
        'contact.formTitle': 'Send a Message',
        'contact.nameLabel': 'Your Name',
        'contact.emailLabel': 'Email Address',
        'contact.subjectLabel': 'Subject',
        'contact.messageLabel': 'Message Content',
        'contact.submitBtn': 'Send Message',
        'contact.infoTitle': 'Contact Information',
        'contact.email': 'Email: contact@dansworld.com',
        'contact.phone': 'Phone: +49 123 4567 8910',
        'contact.address': 'Address: Berlin Art District, Germany',
        'contact.facebook': 'Facebook',
        'contact.instagram': 'Instagram',
        'contact.twitter': 'Twitter',
        'contact.youtube': 'YouTube',
        'contact.form.name': 'Name',
        'contact.form.email': 'Email',
        'contact.form.message': 'Message',
        'contact.form.submit': 'Submit'
    },
    'de': {
        'nav.home': 'Startseite',
        'nav.about': 'Über mich',
        'nav.media': 'Medienzentrum',
        'nav.schedule': 'Aufführungsplan',
        'nav.contact': 'Kontakt',
        'hero.title': 'Willkommen in meiner Welt',
        'hero.subtitle': 'Erkundung der Verschmelzung von Kunst, Musik und Kultur',
        'hero.button': 'Mehr erfahren',
        'about.title': 'Über mich',
        'about.subtitle': 'Künstlerischer Lebensweg',
        'about.text1': 'Ich bin ein professioneller Künstler mit Leidenschaft für Kunst und Musik...',
        'about.text2': 'Meine Werke vereinen Elemente östlicher und westlicher Kulturen...',
        'about.bio1': 'Ich bin ein leidenschaftlicher Künstler, der sich der Verschmelzung klassischer Ästhetik mit modernen Elementen widmet, um einzigartige künstlerische Erfahrungen zu schaffen. Über die Jahre habe ich in den Bereichen Musik, Tanz und bildende Kunst erforscht und nach expressiven Wegen gesucht, traditionelle Grenzen zu überschreiten.',
        'about.bio2': 'Meine Werke wurden in verschiedenen Ländern Europas, Asiens und Nordamerikas ausgestellt und aufgeführt und haben weit verbreitetes Anerkenntnis und Lob erhalten. Ich glaube an die Kraft der Kunst, Sprach- und kulturelle Barrieren zu überwinden und Menschen unterschiedlicher Herkunft zu verbinden.',
        'about.bio3': 'Neben der Kunstschaffung bin ich auch leidenschaftlich für Kunstbildung und kulturellen Austausch engagiert. Ich habe an mehreren Kunstinstitutionen als Gastdozent gearbeitet und an zahlreichen internationalen kulturellen Austauschprogrammen teilgenommen, in der Hoffnung, mehr junge Menschen zu begeistern, sich für Kunst zu interessieren und selbst kreativ zu werden.',
        'about.resumeCn': 'Chinesisches Lebenslauf herunterladen',
        'about.resumeEn': 'Englischen Lebenslauf herunterladen',
        'about.achievements': 'Erfolge und Auszeichnungen',
        'about.achievement1': '2022 Goldener Preis der Internationalen Kunstmesse',
        'about.achievement2': '2020 Preis für den Beitrag zum Europäischen kulturellen Austausch',
        'about.achievement3': '2018 Asischer junge Künstlerpreis',
        'about.achievement4': '2016 Preis für die beste Komposition beim Weltmusikwettbewerb',
        'features.title': 'Kunstwerke',
        'features.item1.title': 'Musikschaffung',
        'features.item1.desc': 'Originale Musikwerke, die klassische und moderne Elemente verbinden',
        'features.item2.title': 'Bühnenaufführung',
        'features.item2.desc': 'Leidenschaftliche und kreative Live-Aufführungen',
        'features.item3.title': 'Kulturelle Exploration',
        'features.item3.desc': 'Künstlerischer Austausch und Erforschung verschiedener Kulturen',
        'media.title': 'Medienzentrum',
        'media.description': 'Hier sind meine neuesten Auftrittsvideos und Medieninhalte',
        'media.featured': 'Ausgewähltes Video',
        'media.featuredCaption': 'Neuester Musikvideo "Melodie der Kunst"',
        'media.gallery': 'Videogalerie',
        'media.video1.title': 'Neuester Auftritt',
        'media.video1.description': 'Frühlingskonzert 2025 Live',
        'media.video1.date': '15. März 2023',
        'media.video2.title': 'Dokumentation des Schaffungsprozesses',
        'media.video2.date': '22. Januar 2023',
        'media.video3.title': 'Künstlerinterview',
        'media.video3.date': '10. November 2022',
        'media.video4.title': 'Backstage - Tonstudio',
        'media.video4.date': '5. September 2022',
        'schedule.title': 'Aufführungsplan',
        'schedule.description': 'Schauen Sie sich meine bevorstehenden Aufführungen und Veranstaltungen an',
        'schedule.dateHeader': 'Datum',
        'schedule.eventHeader': 'Veranstaltung',
        'schedule.locationHeader': 'Ort',
        'schedule.ticketHeader': 'Tickets',
        'schedule.event1.date': '15. Oktober 2023',
        'schedule.event1.location': 'Nationales Zentrum für Darstellende Künste, Peking',
        'schedule.event1.description': 'Frühlingskonzert',
        'schedule.event1': 'Klassisches Musikkonzert',
        'schedule.location1': 'Berliner Konzerthalle',
        'schedule.event2.date': '2. November 2024',
        'schedule.event2.location': 'Shanghai Konzerthalle',
        'schedule.event2.description': 'Solo-Recital',
        'schedule.event2': 'Moderner Tanzaufführung',
        'schedule.location2': 'Paris Opernhaus',
        'schedule.event3': 'Kunstausstellungsöffnung',
        'schedule.location3': 'Nationalgalerie London',
        'schedule.event3.date': '20. November 2025',
        'schedule.event4': 'Neujahrskonzert',
        'schedule.location4': 'Wiener Goldener Saal',
        'schedule.event4.date': '5. Dezember 2024',
        'schedule.event5': 'Asien-Tournee - Peking',
        'schedule.location5': 'Nationales Zentrum für Darstellende Künste, Peking',
        'schedule.event5.date': '18. Januar 2026',
        'schedule.ticketButton': 'Tickets kaufen',
        'schedule.reserveButton': 'Reservieren',
        'schedule.comingSoonButton': 'Bald verfügbar',
        'schedule.detailsButton': 'Veranstaltungsdetails',
        'contact.title': 'Kontakt',
        'contact.description': 'Wenn Sie Fragen haben oder Kooperationsabsichten, kontaktieren Sie mich bitte',
        'contact.formTitle': 'Nachricht senden',
        'contact.nameLabel': 'Ihr Name',
        'contact.emailLabel': 'E-Mail-Adresse',
        'contact.subjectLabel': 'Betreff',
        'contact.messageLabel': 'Nachrichtentext',
        'contact.submitBtn': 'Nachricht senden',
        'contact.infoTitle': 'Kontaktinformationen',
        'contact.email': 'E-Mail: contact@dansworld.com',
        'contact.phone': 'Telefon: +49 123 4567 8910',
        'contact.address': 'Adresse: Berliner Kunstbezirk, Deutschland',
        'contact.facebook': 'Facebook',
        'contact.instagram': 'Instagram',
        'contact.twitter': 'Twitter',
        'contact.youtube': 'YouTube',
        'contact.form.name': 'Name',
        'contact.form.email': 'E-Mail',
        'contact.form.message': 'Nachricht',
        'contact.form.submit': 'Senden'
    }
};

// 语言切换功能
function changeLanguage(lang) {
    // 保存语言设置到localStorage
    localStorage.setItem('preferredLanguage', lang);
    
    // 更新按钮激活状态
    document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
    document.querySelector(`.lang-btn[data-lang="${lang}"]`).classList.add('active');
    
    // 更新页面文本
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.dataset.i18n;
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}

// 语言切换按钮事件监听
document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        const lang = this.dataset.lang;
        changeLanguage(lang);
    });
});

// 页面加载时初始化语言
window.addEventListener('DOMContentLoaded', function() {
    // 从localStorage获取首选语言，如果没有则使用英文作为默认语言
    const savedLang = localStorage.getItem('preferredLanguage') || 'en';
    
    // 检查保存的语言是否在支持的语言列表中
    if (translations[savedLang]) {
        changeLanguage(savedLang);
    } else {
        // 如果保存的语言不支持，则使用英文
        changeLanguage('en');
    }
});